name: Docs nightly checks
'on':
  schedule:
  - cron: 0 6 * * *
jobs:
  snapshots:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'cidsod7z'
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        sparse-checkout: /docs/
        sparse-checkout-cone-mode: false
    - name: Run all snapshots
      run: ./docs/updateSnapshots -t edge -a
    - name: Upload error logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: snapshot-error-logs
        path: docs/snapshotter/errors/
  validation:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'cidsod7z'
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        sparse-checkout: /docs/
        sparse-checkout-cone-mode: false
    - name: Check formatting
      run: ./docs/format -c
    - name: Validate docs
      if: always()
      run: ./docs/validate -e
    - name: Upload error logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: validator-error-logs
        path: docs/validator-results/
  slack-notify:
    runs-on: ubuntu-24.04
    needs:
    - snapshots
    - validation
    if: failure() && github.ref == 'refs/heads/main' && github.repository_owner ==
      'cidsod7z'
    steps:
    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEVREL}}
      with:
        payload: "{\n  \"repository\": \"${{ github.repository }}\",\n  \"message\"\
          : \"${{ github.workflow }}/${{ github.job }} nightly check failure\",\n\
          \  \"link\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{\
          \ github.run_id }}\"\n}"
